// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi.Utilities;

namespace Pulumi.Vultr
{
    public static class GetDnsDomain
    {
        /// <summary>
        /// Get information about a DNS domain associated with your Vultr account.
        /// 
        /// {{% examples %}}
        /// ## Example Usage
        /// {{% example %}}
        /// 
        /// Get the information for a DNS domain:
        /// 
        /// ```csharp
        /// using Pulumi;
        /// using Vultr = Pulumi.Vultr;
        /// 
        /// class MyStack : Stack
        /// {
        ///     public MyStack()
        ///     {
        ///         var myDomain = Output.Create(Vultr.GetDnsDomain.InvokeAsync(new Vultr.GetDnsDomainArgs
        ///         {
        ///             Domain = "example.com",
        ///         }));
        ///     }
        /// 
        /// }
        /// ```
        /// {{% /example %}}
        /// {{% /examples %}}
        /// </summary>
        public static Task<GetDnsDomainResult> InvokeAsync(GetDnsDomainArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetDnsDomainResult>("vultr:index/getDnsDomain:getDnsDomain", args ?? new GetDnsDomainArgs(), options.WithVersion());

        /// <summary>
        /// Get information about a DNS domain associated with your Vultr account.
        /// 
        /// {{% examples %}}
        /// ## Example Usage
        /// {{% example %}}
        /// 
        /// Get the information for a DNS domain:
        /// 
        /// ```csharp
        /// using Pulumi;
        /// using Vultr = Pulumi.Vultr;
        /// 
        /// class MyStack : Stack
        /// {
        ///     public MyStack()
        ///     {
        ///         var myDomain = Output.Create(Vultr.GetDnsDomain.InvokeAsync(new Vultr.GetDnsDomainArgs
        ///         {
        ///             Domain = "example.com",
        ///         }));
        ///     }
        /// 
        /// }
        /// ```
        /// {{% /example %}}
        /// {{% /examples %}}
        /// </summary>
        public static Output<GetDnsDomainResult> Invoke(GetDnsDomainInvokeArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.Invoke<GetDnsDomainResult>("vultr:index/getDnsDomain:getDnsDomain", args ?? new GetDnsDomainInvokeArgs(), options.WithVersion());
    }


    public sealed class GetDnsDomainArgs : Pulumi.InvokeArgs
    {
        /// <summary>
        /// The name you're searching for.
        /// </summary>
        [Input("domain", required: true)]
        public string Domain { get; set; } = null!;

        public GetDnsDomainArgs()
        {
        }
    }

    public sealed class GetDnsDomainInvokeArgs : Pulumi.InvokeArgs
    {
        /// <summary>
        /// The name you're searching for.
        /// </summary>
        [Input("domain", required: true)]
        public Input<string> Domain { get; set; } = null!;

        public GetDnsDomainInvokeArgs()
        {
        }
    }


    [OutputType]
    public sealed class GetDnsDomainResult
    {
        /// <summary>
        /// The date the DNS domain was added to your Vultr account.
        /// </summary>
        public readonly string DateCreated;
        /// <summary>
        /// The Domain's DNSSEC status
        /// </summary>
        public readonly string DnsSec;
        /// <summary>
        /// Name of domain.
        /// </summary>
        public readonly string Domain;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;

        [OutputConstructor]
        private GetDnsDomainResult(
            string dateCreated,

            string dnsSec,

            string domain,

            string id)
        {
            DateCreated = dateCreated;
            DnsSec = dnsSec;
            Domain = domain;
            Id = id;
        }
    }
}
