// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi.Utilities;

namespace Pulumi.Vultr
{
    public static class GetSshKey
    {
        /// <summary>
        /// Get information about a Vultr SSH key. This data source provides the name, public SSH key, and the creation date for your Vultr SSH key.
        /// 
        /// {{% examples %}}
        /// ## Example Usage
        /// {{% example %}}
        /// 
        /// Get the information for an SSH key by `name`:
        /// 
        /// ```csharp
        /// using Pulumi;
        /// using Vultr = Pulumi.Vultr;
        /// 
        /// class MyStack : Stack
        /// {
        ///     public MyStack()
        ///     {
        ///         var mySshKey = Output.Create(Vultr.GetSshKey.InvokeAsync(new Vultr.GetSshKeyArgs
        ///         {
        ///             Filters = 
        ///             {
        ///                 new Vultr.Inputs.GetSshKeyFilterArgs
        ///                 {
        ///                     Name = "name",
        ///                     Values = 
        ///                     {
        ///                         "my-ssh-key-name",
        ///                     },
        ///                 },
        ///             },
        ///         }));
        ///     }
        /// 
        /// }
        /// ```
        /// {{% /example %}}
        /// {{% /examples %}}
        /// </summary>
        public static Task<GetSshKeyResult> InvokeAsync(GetSshKeyArgs? args = null, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetSshKeyResult>("vultr:index/getSshKey:getSshKey", args ?? new GetSshKeyArgs(), options.WithVersion());

        /// <summary>
        /// Get information about a Vultr SSH key. This data source provides the name, public SSH key, and the creation date for your Vultr SSH key.
        /// 
        /// {{% examples %}}
        /// ## Example Usage
        /// {{% example %}}
        /// 
        /// Get the information for an SSH key by `name`:
        /// 
        /// ```csharp
        /// using Pulumi;
        /// using Vultr = Pulumi.Vultr;
        /// 
        /// class MyStack : Stack
        /// {
        ///     public MyStack()
        ///     {
        ///         var mySshKey = Output.Create(Vultr.GetSshKey.InvokeAsync(new Vultr.GetSshKeyArgs
        ///         {
        ///             Filters = 
        ///             {
        ///                 new Vultr.Inputs.GetSshKeyFilterArgs
        ///                 {
        ///                     Name = "name",
        ///                     Values = 
        ///                     {
        ///                         "my-ssh-key-name",
        ///                     },
        ///                 },
        ///             },
        ///         }));
        ///     }
        /// 
        /// }
        /// ```
        /// {{% /example %}}
        /// {{% /examples %}}
        /// </summary>
        public static Output<GetSshKeyResult> Invoke(GetSshKeyInvokeArgs? args = null, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.Invoke<GetSshKeyResult>("vultr:index/getSshKey:getSshKey", args ?? new GetSshKeyInvokeArgs(), options.WithVersion());
    }


    public sealed class GetSshKeyArgs : Pulumi.InvokeArgs
    {
        [Input("filters")]
        private List<Inputs.GetSshKeyFilterArgs>? _filters;

        /// <summary>
        /// Query parameters for finding SSH keys.
        /// </summary>
        public List<Inputs.GetSshKeyFilterArgs> Filters
        {
            get => _filters ?? (_filters = new List<Inputs.GetSshKeyFilterArgs>());
            set => _filters = value;
        }

        public GetSshKeyArgs()
        {
        }
    }

    public sealed class GetSshKeyInvokeArgs : Pulumi.InvokeArgs
    {
        [Input("filters")]
        private InputList<Inputs.GetSshKeyFilterInputArgs>? _filters;

        /// <summary>
        /// Query parameters for finding SSH keys.
        /// </summary>
        public InputList<Inputs.GetSshKeyFilterInputArgs> Filters
        {
            get => _filters ?? (_filters = new InputList<Inputs.GetSshKeyFilterInputArgs>());
            set => _filters = value;
        }

        public GetSshKeyInvokeArgs()
        {
        }
    }


    [OutputType]
    public sealed class GetSshKeyResult
    {
        /// <summary>
        /// The date the SSH key was added to your Vultr account.
        /// </summary>
        public readonly string DateCreated;
        public readonly ImmutableArray<Outputs.GetSshKeyFilterResult> Filters;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// The name of the SSH key.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// The public SSH key.
        /// </summary>
        public readonly string Key;

        [OutputConstructor]
        private GetSshKeyResult(
            string dateCreated,

            ImmutableArray<Outputs.GetSshKeyFilterResult> filters,

            string id,

            string name,

            string sshKey)
        {
            DateCreated = dateCreated;
            Filters = filters;
            Id = id;
            Name = name;
            Key = sshKey;
        }
    }
}
