// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Provides a Vultr instance IPv4 resource. This can be used to create, read, and
 * modify a IPv4 address. instance is rebooted by default.
 *
 * ## Example Usage
 *
 * Create a new IPv4 address for a instance:
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as vultr from "@pulumi/vultr";
 *
 * const myInstance = new vultr.Instance("my_instance", {
 *     enableIpv6: true,
 *     osId: 167,
 *     plan: "vc2-1c-1gb",
 *     region: "ewr",
 * });
 * const myInstanceIpv4 = new vultr.InstanceIPv4("my_instance_ipv4", {
 *     instanceId: myInstance.id,
 *     reboot: false,
 * });
 * ```
 */
export class InstanceIPv4 extends pulumi.CustomResource {
    /**
     * Get an existing InstanceIPv4 resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: InstanceIPv4State, opts?: pulumi.CustomResourceOptions): InstanceIPv4 {
        return new InstanceIPv4(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'vultr:index/instanceIPv4:InstanceIPv4';

    /**
     * Returns true if the given object is an instance of InstanceIPv4.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is InstanceIPv4 {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === InstanceIPv4.__pulumiType;
    }

    /**
     * The gateway IP address.
     */
    public /*out*/ readonly gateway!: pulumi.Output<string>;
    /**
     * The ID of the instance to be assigned the IPv4 address.
     */
    public readonly instanceId!: pulumi.Output<string>;
    /**
     * The IPv4 address in canonical format.
     */
    public /*out*/ readonly ip!: pulumi.Output<string>;
    /**
     * The IPv4 netmask in dot-decimal notation.
     */
    public /*out*/ readonly netmask!: pulumi.Output<string>;
    /**
     * Default true. Determines whether or not the server is rebooted after adding the IPv4 address.
     */
    public readonly reboot!: pulumi.Output<boolean | undefined>;
    /**
     * The reverse DNS information for this IP address.
     */
    public /*out*/ readonly reverse!: pulumi.Output<string>;

    /**
     * Create a InstanceIPv4 resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: InstanceIPv4Args, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: InstanceIPv4Args | InstanceIPv4State, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as InstanceIPv4State | undefined;
            resourceInputs["gateway"] = state ? state.gateway : undefined;
            resourceInputs["instanceId"] = state ? state.instanceId : undefined;
            resourceInputs["ip"] = state ? state.ip : undefined;
            resourceInputs["netmask"] = state ? state.netmask : undefined;
            resourceInputs["reboot"] = state ? state.reboot : undefined;
            resourceInputs["reverse"] = state ? state.reverse : undefined;
        } else {
            const args = argsOrState as InstanceIPv4Args | undefined;
            if ((!args || args.instanceId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'instanceId'");
            }
            resourceInputs["instanceId"] = args ? args.instanceId : undefined;
            resourceInputs["reboot"] = args ? args.reboot : undefined;
            resourceInputs["gateway"] = undefined /*out*/;
            resourceInputs["ip"] = undefined /*out*/;
            resourceInputs["netmask"] = undefined /*out*/;
            resourceInputs["reverse"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(InstanceIPv4.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering InstanceIPv4 resources.
 */
export interface InstanceIPv4State {
    /**
     * The gateway IP address.
     */
    gateway?: pulumi.Input<string>;
    /**
     * The ID of the instance to be assigned the IPv4 address.
     */
    instanceId?: pulumi.Input<string>;
    /**
     * The IPv4 address in canonical format.
     */
    ip?: pulumi.Input<string>;
    /**
     * The IPv4 netmask in dot-decimal notation.
     */
    netmask?: pulumi.Input<string>;
    /**
     * Default true. Determines whether or not the server is rebooted after adding the IPv4 address.
     */
    reboot?: pulumi.Input<boolean>;
    /**
     * The reverse DNS information for this IP address.
     */
    reverse?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a InstanceIPv4 resource.
 */
export interface InstanceIPv4Args {
    /**
     * The ID of the instance to be assigned the IPv4 address.
     */
    instanceId: pulumi.Input<string>;
    /**
     * Default true. Determines whether or not the server is rebooted after adding the IPv4 address.
     */
    reboot?: pulumi.Input<boolean>;
}
